exports.amenities = [
  { "name": "Swimming Pool", "slug": "swimming_pool", "icon": "fa-swimming-pool",isDeleted: false },
  { "name": "Gym / Fitness Center", "slug": "gym", "icon": "fa-dumbbell",isDeleted: false },
  { "name": "24x7 Security", "slug": "security", "icon": "fa-shield-alt",isDeleted: false },
  { "name": "Power Backup", "slug": "power_backup", "icon": "fa-bolt",isDeleted: false },
  { "name": "Lift / Elevator", "slug": "lift", "icon": "fa-elevator",isDeleted: false },
  { "name": "Parking (Car/Bike)", "slug": "parking", "icon": "fa-car",isDeleted: false },
  { "name": "Children’s Play Area", "slug": "play_area", "icon": "fa-child",isDeleted: false },
  { "name": "Garden / Park", "slug": "garden", "icon": "fa-tree",isDeleted: false },
  { "name": "Clubhouse", "slug": "clubhouse", "icon": "fa-house-user",isDeleted: false },
  { "name": "Community Hall", "slug": "community_hall", "icon": "fa-users",isDeleted: false },
  { "name": "Jogging Track", "slug": "jogging_track", "icon": "fa-shoe-prints",isDeleted: false },
  { "name": "Indoor Games", "slug": "indoor_games", "icon": "fa-chess-board",isDeleted: false },
  { "name": "Wi-Fi Connectivity", "slug": "wifi", "icon": "fa-wifi",isDeleted: false },
  { "name": "CCTV Surveillance", "slug": "cctv", "icon": "fa-video",isDeleted: false },
  { "name": "Fire Safety", "slug": "fire_safety", "icon": "fa-fire-extinguisher",isDeleted: false },
  { "name": "Intercom Facility", "slug": "intercom", "icon": "fa-phone",isDeleted: false },
  { "name": "Rain Water Harvesting", "slug": "rainwater_harvesting", "icon": "fa-cloud-rain",isDeleted: false },
  { "name": "Waste Disposal", "slug": "waste_disposal", "icon": "fa-dumpster",isDeleted: false },
  { "name": "Laundry Service", "slug": "laundry", "icon": "fa-soap",isDeleted: false },
  { "name": "Maintenance Staff", "slug": "maintenance", "icon": "fa-tools",isDeleted: false },
  { "name": "Vaastu Compliant", "slug": "vaastu_compliant", "icon": "fa-compass",isDeleted: false },
  { "name": "Shopping Center", "slug": "shopping_center", "icon": "fa-shopping-bag",isDeleted: false },
  { "name": "Gated Community", "slug": "gated_community", "icon": "fa-door-closed",isDeleted: false },
  { "name": "Pet Friendly", "slug": "pet_friendly", "icon": "fa-paw",isDeleted: false },
  { "name": "Air Conditioning", "slug": "air_conditioning", "icon": "fa-snowflake",isDeleted: false },
  { "name": "Servant Room", "slug": "servant_room", "icon": "fa-user-tie",isDeleted: false },
  { "name": "Visitor Parking", "slug": "visitor_parking", "icon": "fa-parking",isDeleted: false },
  { "name": "ATM / Banking", "slug": "atm", "icon": "fa-university",isDeleted: false },
  { "name": "Conference Room", "slug": "conference_room", "icon": "fa-handshake",isDeleted: false },
  { "name": "Roof Terrace", "slug": "roof_terrace", "icon": "fa-building",isDeleted: false }
]
