exports.amenities = [
  { "name": "Swimming Pool", "slug": "swimming_pool", "icon": "fa-swimming-pool" },
  { "name": "Gym / Fitness Center", "slug": "gym", "icon": "fa-dumbbell" },
  { "name": "24x7 Security", "slug": "security", "icon": "fa-shield-alt" },
  { "name": "Power Backup", "slug": "power_backup", "icon": "fa-bolt" },
  { "name": "Lift / Elevator", "slug": "lift", "icon": "fa-elevator" },
  { "name": "Parking (Car/Bike)", "slug": "parking", "icon": "fa-car" },
  { "name": "Children’s Play Area", "slug": "play_area", "icon": "fa-child" },
  { "name": "Garden / Park", "slug": "garden", "icon": "fa-tree" },
  { "name": "Clubhouse", "slug": "clubhouse", "icon": "fa-house-user" },
  { "name": "Community Hall", "slug": "community_hall", "icon": "fa-users" },
  { "name": "Jogging Track", "slug": "jogging_track", "icon": "fa-shoe-prints" },
  { "name": "Indoor Games", "slug": "indoor_games", "icon": "fa-chess-board" },
  { "name": "Wi-Fi Connectivity", "slug": "wifi", "icon": "fa-wifi" },
  { "name": "CCTV Surveillance", "slug": "cctv", "icon": "fa-video" },
  { "name": "Fire Safety", "slug": "fire_safety", "icon": "fa-fire-extinguisher" },
  { "name": "Intercom Facility", "slug": "intercom", "icon": "fa-phone" },
  { "name": "Rain Water Harvesting", "slug": "rainwater_harvesting", "icon": "fa-cloud-rain" },
  { "name": "Waste Disposal", "slug": "waste_disposal", "icon": "fa-dumpster" },
  { "name": "Laundry Service", "slug": "laundry", "icon": "fa-soap" },
  { "name": "Maintenance Staff", "slug": "maintenance", "icon": "fa-tools" },
  { "name": "Vaastu Compliant", "slug": "vaastu_compliant", "icon": "fa-compass" },
  { "name": "Shopping Center", "slug": "shopping_center", "icon": "fa-shopping-bag" },
  { "name": "Gated Community", "slug": "gated_community", "icon": "fa-door-closed" },
  { "name": "Pet Friendly", "slug": "pet_friendly", "icon": "fa-paw" },
  { "name": "Air Conditioning", "slug": "air_conditioning", "icon": "fa-snowflake" },
  { "name": "Servant Room", "slug": "servant_room", "icon": "fa-user-tie" },
  { "name": "Visitor Parking", "slug": "visitor_parking", "icon": "fa-parking" },
  { "name": "ATM / Banking", "slug": "atm", "icon": "fa-university" },
  { "name": "Conference Room", "slug": "conference_room", "icon": "fa-handshake" },
  { "name": "Roof Terrace", "slug": "roof_terrace", "icon": "fa-building" }
]
